django/login_and_reg_old/apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^this_app/register$',views.register_user,name='register_user'),
	url(r'^this_app/login$',views.login_user,name='login_user'),
	url(r'^this_app/logout',views.logout_user,name='logout_user'),
]

django/login_and_reg_old/login_and_reg/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.login_reg.urls',namespace='login_reg')),
]

django/login_and_reg_old/apps/login_reg/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
import re
import bcrypt

# Create your models here.

class UserManager(models.Manager):
    def validate_login(self, **kwargs):
        print "Made it into the user login validation"
        errors = []
        try:
            query = User.objects.get(email=kwargs['email_address'])
            if bcrypt.hashpw(kwargs['password'].encode('utf-8'),query.password.encode('utf-8')) == query.password:
                #we found and matched the password
                return (True,query)
            else:
                errors.append('Password is incorrect')
                return (False,errors)
        except ObjectDoesNotExist:
            errors.append(str(kwargs['email_address'])+' does not exist in the database.')
            return (False,errors)

    def validate_registration(self, **kwargs):
        print "Made it into the user registration validation"
        errors = []
        NAME_REGEX = re.compile(r'[a-zA-Z_-]+$')
        #check first name
        if len(kwargs['first_name']) < 2:
            errors.append('First name cannot be less than two characters.')
        if not NAME_REGEX.match(kwargs['first_name']):
            errors.append('Your first name can\'t contain any thing but letters silly.')

        #check last name
        if len(kwargs['last_name']) < 2:
            errors.append('Last name cannot be less than two characters.')
        if not NAME_REGEX.match(kwargs['last_name']):
            errors.append('Your last name can\'t contain any thing but letters silly.')

        #regex: email verification stirng
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
        #check email
        if len(kwargs['email_address']) < 1:
            errors.append('We would really like to spam your inbox, please provide your email')
        if not EMAIL_REGEX.match(kwargs['email_address']):
            errors.append('This is not a valid email, try again!')
        try:
            query = User.objects.get(email=kwargs['email_address'])
            if query.email:
                errors.append('Email address already exists in the database.')
        except ObjectDoesNotExist:
            # pass, means users email is not in the DB already
            pass


        #check password length
        if len(kwargs['password']) < 8 or len(kwargs['confirm_password']) < 8:
            errors.append('Password must be a minimum of 8 characters long.')
        else: #check hash of password = hash of confirm password
            pw_hash = bcrypt.hashpw(kwargs['password'].encode('utf-8'),bcrypt.gensalt())
            if bcrypt.hashpw(kwargs['confirm_password'].encode('utf-8'),pw_hash) != pw_hash:
                errors.append('Passwords do not match')

        if not errors:
            user = User.objects.create(first_name=kwargs['first_name'],last_name=kwargs['last_name'],email=kwargs['email_address'],password=pw_hash)
            return (True,user)
        else:
            return (False,errors)

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

django/login_and_reg_old/apps/login_reg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.template.loader import get_template, render_to_string
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    #check if logged in
    if 'id' in request.session:
        #render landing page
        context = {
            'content' : render_to_string('login_reg/partials/landing.html', {'user' : User.objects.get(id=request.session['id']).first_name},request=request,),
        }
    else:
        #render login/registration page
        context = {
            'content':render_to_string('login_reg/partials/forms.html',request=request,)
        }
    return render(request, 'login_reg/index.html',context)

def register_user(request):
    if request.method == "POST":
        print "registering user"
        #clean this up...
        response = User.objects.validate_registration(first_name=request.POST['first_name'],last_name=request.POST['last_name'],email_address=request.POST['email_address'],password=request.POST['password'],confirm_password=request.POST['confirm_password'])
        if response[0]:
            #pass information to our partials form and load
            context = {
                'content':render_to_string('login_reg/partials/landing.html',{'user' : response[1].first_name,'action':'register',},request=request,)
            }
            if 'id' not in request.session:
                request.session['id'] = response[1].id
            return render(request, 'login_reg/index.html',context)
        else:
            for error in response[1]:
                messages.error(request, error)
            # here we could just do a redirect('/') but if we want to pass back some values so the user does not need to re-enter them then we have to do the below
            context = {
                'content':render_to_string('login_reg/partials/forms.html',{'first_name':request.POST['first_name'],'last_name':request.POST['last_name'],'email_address':request.POST['email_address'],},request=request),
            }
            return render(request,'login_reg/index.html',context)
            # return redirect(reverse('login_reg:index'))
    else:
        return redirect(reverse('login_reg:index'))

def login_user(request):
    #verify not already logged in
    if 'id' not in request.session:
        response = User.objects.validate_login(email_address=request.POST['login_email'],password=request.POST['login_password'])
        if response[0]:
            context = {
                'content':render_to_string('login_reg/partials/landing.html',{'user' : response[1].first_name,'action':'login',}),
            }
            if 'id' not in request.session:
                request.session['id'] = response[1].id
            return render(request, 'login_reg/index.html',context)
        else:
            for error in response[1]:
                messages.error(request, error)
            return redirect(reverse('login_reg:index'))
    else:
        #just so we don't crash our server...
        return redirect(reverse('login_reg:index'))


def logout_user(request):
    #logout...
    if 'id' in request.session:
        print "popping session"
        del request.session['id']
    return redirect(reverse('login_reg:index'))

django/login_and_reg_old/apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Register</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_reg/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            {{content|safe}}
        </div>
    </body>
</html>

django/login_and_reg_old/apps/login_reg/templates/login_reg/partials/forms.html
{% for message in messages %}
    <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}
<form name="register" method="POST" action="{% url 'login_reg:register_user' %}">
    {% csrf_token %}
    <p>
        <label>First Name: </label><input type="text" name="first_name" value="{{first_name}}"/>
    </p>
    <p>
        <label>Last Name: </label><input type="text" name="last_name" value="{{last_name}}"/>
    </p>
    <p>
        <label>Email Address: </label><input type="text"
        name="email_address" value="{{email_address}}"/>
    </p>
    <p>
        <label>Password: </label><input type="password" name="password" />
    </p>
    <p>
        <label>Confirm Password: </label><input type="password" name="confirm_password" />
    </p>
    <p>
        <input type="submit" Value="Register!"/>
    </p>
</form>
<hr>
<form name="login" method="POST" action="{% url 'login_reg:login_user' %}">
    {% csrf_token %}
    <p>
        <label>Email Address: </label><input type="text" name="login_email" value="{{login_email}}" />
    </p>
    <p>
        <label>Password: </label><input type="password" name="login_password" />
    </p>
    <p>
        <input type="submit" value="Login" />
    </p>
</form>

django/login_and_reg_old/apps/login_reg/templates/login_reg/partials/landing.html
<h1>{{user}}</h1>
{% if action == "login" %}
    <p class="success">Succesfully logged in!</p>
{% elif action == "register" %}
    <p class="success">Successfully registered!</p>
{% else %}
    <p class="boring">Welcome back I guess...</p>
{% endif %}
<a href="{% url 'login_reg:logout_user' %}">Logout!</a>