django/multiple_apps/apps/surveyform/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^this_app/surveys/process$',views.process,name='process')
]

django/multiple_apps/multiple_apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.testmodels.urls',namespace='testmodels')),
    url(r'^timedisplay/',include('apps.timedisplay.urls',namespace='timedisplay')),
    url(r'^surveyform/',include('apps.surveyform.urls',namespace='surveyform')),
    url(r'^random_word/',include('apps.random_word.urls',namespace='random_word')),
    url(r'^login_reg/',include('apps.login_reg.urls',namespace='login_reg')),
    url(r'^course_app/',include('apps.course_app.urls',namespace='course_app')),
]

django/multiple_apps/apps/surveyform/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django/multiple_apps/apps/surveyform/views.py
from django.shortcuts import render, HttpResponse, redirect

from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    if 'submit_num' not in request.session:
        request.session['submit_num'] = 0
    return render(request,'surveyform/index.html')

def process(request):
    if 'submit_num' in request.session:
        request.session['submit_num'] += 1
        context = {
            'name' : request.POST['name'],
            'location' : request.POST['location'],
            'language' : request.POST['language'],
            'comment' : request.POST['comment']
        }
        return render(request, 'surveyform/results.html',context)
    else:
        return redirect(reverse('surveyform:index'))

django/multiple_apps/apps/surveyform/templates/surveyform/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Survey Form</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <form method="POST" action="{% url 'surveyform:process' %}">
            {% csrf_token %}
            <p><label>Your Name: </label><input type="text" name="name" /></p>
            <p>
                <label>Dojo Location: </label>
                <select name="location">
                    <option value="Seattle">Seattle</option selected>
                    <option value="London">London</option>
                    <option value="New York">New York</option>
                    <option value="San Diego">San Diego</option>
                </select>
            </p>
            <p>
                <label>Favorite Language: </label>
                <select name="language">
                    <option value="PHP">PHP</option>
                    <option value="Python">Python</option selected>
                    <option value="C++">C++</option>
                    <option value="C#">C#</option>
                </select>
            </p>
            <p><label>Comment (optional):</label></p>
            <textarea name="comment"></textarea>
            <input type="submit" value="Submit" />
        </form>
    </body>
</html>

django/multiple_apps/apps/surveyform/templates/surveyform/results.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Form Results</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <div class="attempts">
            Thanks for submitting this form! You have submitted this form {{request.session.submit_num}} times now.
        </div>
        <div class="contents">
            <h3>Submitted Information:</h3>
            <p><label>Name: </label>{{name}}</p>
            <p><label>Location: </label>{{location}}</p>
            <p><label>Dojo Location: </label>{{language}}</p>
            <p><label>Comment: </label>{{comment}}</p>
            <a href="{% url 'surveyform:index' %}">Go Back</a>
        </div>
    </body>
</html>